/** Centralized metadata for Biolink KnowledgeLevelEnum values. */

type KnowledgeLevelMeta = { icon: string; label: string; description: string };

export const KNOWLEDGE_LEVEL_META: Record<string, KnowledgeLevelMeta> = {
  knowledge_assertion: {
    icon: "circle-check",
    label: "Knowledge Assertion",
    description:
      "Directly asserted by a knowledge source or curator, representing an accepted fact",
  },
  logical_entailment: {
    icon: "sitemap",
    label: "Logical Entailment",
    description:
      "Derived by logical inference or reasoning from other statements",
  },
  prediction: {
    icon: "chart-bar",
    label: "Prediction",
    description:
      "Generated by a predictive or computational model; may be less certain",
  },
  statistical_association: {
    icon: "equals",
    label: "Statistical Association",
    description: "Derived from a statistical association observed in data",
  },
  observation: {
    icon: "eye",
    label: "Observation",
    description: "Based on a direct observation",
  },
  not_provided: {
    icon: "circle-question",
    label: "Not Provided",
    description: "Knowledge level not available",
  },
};

export const KNOWLEDGE_LEVEL_KEYS = Object.keys(KNOWLEDGE_LEVEL_META);

const FALLBACK: KnowledgeLevelMeta = {
  icon: "circle-question",
  label: "Unknown",
  description: "Unrecognized knowledge level",
};

/** Get icon, label, and description for a knowledge_level value. */
export function getKnowledgeLevelMeta(
  knowledgeLevel: string,
): KnowledgeLevelMeta {
  return KNOWLEDGE_LEVEL_META[knowledgeLevel] ?? FALLBACK;
}

/** Format a knowledge_level value as a human-readable label. */
export function formatKnowledgeLevel(knowledgeLevel: string): string {
  return getKnowledgeLevelMeta(knowledgeLevel).label;
}
