export const RESOURCE_NAME_MAP: Record<string, string> = {
  MGI: "Mouse Genome Informatics",
  STRING: "Search Tool for the Retrieval of Interacting Genes/Proteins",
  BIOGRID: "Biological General Repository for Interaction Datasets",
  PANTHER: "Protein ANalysis THrough Evolutionary Relationships",
  ZFIN: "Zebrafish Information Network",
  UNIPROT: "Universal Protein Resource",
  ENSEMBL: "Ensembl Genome Database Project",
  FLYBASE: "FlyBase (Drosophila Genetics & Genomics Database)",
  BGEE: "Bgee: Gene Expression Evolution Database",
  REACTOME: "Reactome Pathway Knowledgebase",
  RGD: "Rat Genome Database",
  UPHENO: "Unified Phenotype Ontology",
  INTERPRO: "InterPro (Protein Families, Domains & Sites)",
  INTACT: "IntAct Molecular Interaction Database",
  POMBASE: "PomBase (Schizosaccharomyces pombe Model Organism Database)",
  OMIM: "Online Mendelian Inheritance in Man",
  FBBT: "Drosophila Anatomy Ontology (FBbt)",
  WORMBASE: "WormBase (Caenorhabditis Genetics & Genomics Database)",
  ORPHANET: "Orphanet (Rare Diseases Resource)",
  XENBASE: "Xenbase (Xenopus Model Organism Database)",
  GO: "Gene Ontology",
  SGD: "Saccharomyces Genome Database",
  CHEBI: "Chemical Entities of Biological Interest (ChEBI)",
  ZP: "Zebrafish Phenotype Ontology",
  PR: "Protein Ontology (PRO)",
  MONDO: "Monarch Disease Ontology (MONDO)",
  OBA: "Ontology of Biological Attributes",
  UBERON: "Uberon Multi-Species Anatomy Ontology",
  XPO: "Xenopus Phenotype Ontology",
  HP: "Human Phenotype Ontology",
  SYNGO: "SynGO (Synaptic Gene Ontology)",
  HPA: "Human Protein Atlas",
  GOC: "Gene Ontology Consortium",
  CLINVAR: "ClinVar (Clinical Variants Resource)",
  DICTYBASE: "dictyBase (Dictyostelium Model Organism Database)",
  WBBT: "WormBase Anatomy Ontology (WBbt)",
  MP: "Mammalian Phenotype Ontology",
  CTD: "Comparative Toxicogenomics Database",
  WB: "WormBase",
  COMPLEXPORTAL: "Complex Portal (Macromolecular Complexes, EMBL-EBI)",
  RHEA: "Rhea Biochemical Reactions Knowledgebase",
  CLINGEN: "Clinical Genome Resource (ClinGen)",
  ZFA: "Zebrafish Anatomy Ontology (ZFA)",
  PINC: "Protein Interaction Network Curations",
  FYPO: "Fission Yeast Phenotype Ontology",
  EMAPA: "Mouse Developmental Anatomy Ontology (EMAPA)",
  CL: "Cell Ontology",
  AGBASE: "AgBase (Functional Genomics for Agriculture)",
  XAO: "Xenopus Anatomy Ontology",
  MAXO: "Medical Action Ontology",
  CAFA: "Critical Assessment of Functional Annotation",
  WBPHENOTYPE: "WormBase Phenotype Ontology",
  NCBITAXON: "NCBI Taxonomy",
  RNACENTRAL: "RNAcentral (Non-coding RNA Sequence Database)",
  CACAO: "Community Assessment of Community Annotation with Ontologies",
  PATO: "Phenotype and Trait Ontology",
  DDPHENO: "Dictyostelium discoideum Phenotype Ontology",
  DISPROT: "DisProt (Database of Protein Disorder)",
  HSAPDV: "Human Developmental Stages Ontology (HsapDv)",
  DFLAT: "Developmental FunctionaL Annotation at Tufts",
  NBO: "Neurobehavior Ontology",
  YUBIOLAB: "YuBioLab Gene Ontology Annotation",
  FBDV: "FlyBase Drosophila Development Ontology",
  "GO-CENTRAL": "Gene Ontology Central",
  "ARUK-UCL": "Alzheimer’s Research UK – UCL Gene Ontology Annotation",
  "PARKINSONSUK-UCL": "Parkinson’s UK – UCL Gene Ontology Annotation",
  "HGNC-UCL": "HGNC – UCL Gene Ontology Annotation",
  "NTNU-SB": "NTNU Systems Biology Gene Ontology Annotation",
  LIFEDB: "Localization and Interaction Explorer Database (LIFEdb)",
  RO: "Relations Ontology",
  DDANAT: "Dictyostelium Anatomy Ontology",
  HGNC: "HUGO Gene Nomenclature Committee",
  FBCV: "FlyBase Controlled Vocabulary",
  SO: "Sequence Ontology",
  MPATH: "Mouse Pathology Ontology",
  "SYSCILIA-CCNET": "Syscilia Ciliopathy Network Dataset",
  WBLS: "WormBase Life Stage Ontology",
  GDB: "GDB Human Genome Database",
  "SYNGO-UCL": "SynGO – UCL Gene Ontology Annotation",
  ZFS: "Zebrafish Stage Ontology",
  "ROSLIN-INSTITUTE":
    "The Roslin Institute – University of Edinburgh GO Annotation",
  BFO: "Basic Formal Ontology",
  MTBBASE: "Mouse Tumor Biology Database",
  "GOC-OWL": "Gene Ontology OWL Builds",
  "GO-NOCTUA": "GO Noctua Curation Platform",
  DIBU: "Unknown/placeholder label (no authoritative expansion available)",
  "PHI-BASE": "Pathogen–Host Interactions Database",
  ALLIANCEGENOME: "Alliance of Genome Resources",
  AGRKB: "Alliance of Genome Resources Knowledgebase",
  PHENIO: "Phenio (Integrated Cross-Species Phenotype Ontology)",
  "HPO-ANNOTATIONS": "Human Phenotype Ontology Annotations",
  MEDGEN: "MedGen (NCBI Medical Genetics Portal)",
};
