from enum import Enum


class EntityCategory(Enum):
    """Entity categories"""

    GENE = "Gene"
    PHENOTYPICFEATURE = "PhenotypicFeature"
    BIOLOGICALPROCESSORACTIVITY = "BiologicalProcessOrActivity"
    GROSSANATOMICALSTRUCTURE = "GrossAnatomicalStructure"
    DISEASE = "Disease"
    PATHWAY = "Pathway"
    CELL = "Cell"
    NAMEDTHING = "NamedThing"
    ANATOMICALENTITY = "AnatomicalEntity"
    CELLULARCOMPONENT = "CellularComponent"
    MOLECULARENTITY = "MolecularEntity"
    BIOLOGICALPROCESS = "BiologicalProcess"
    MACROMOLECULARCOMPLEX = "MacromolecularComplex"
    MOLECULARACTIVITY = "MolecularActivity"
    PROTEIN = "Protein"
    CELLULARORGANISM = "CellularOrganism"
    PHENOTYPICQUALITY = "PhenotypicQuality"
    VERTEBRATE = "Vertebrate"
    VIRUS = "Virus"
    BEHAVIORALFEATURE = "BehavioralFeature"
    LIFESTAGE = "LifeStage"
    PATHOLOGICALPROCESS = "PathologicalProcess"
    CHEMICALENTITY = "ChemicalEntity"
    DRUG = "Drug"
    INFORMATIONCONTENTENTITY = "InformationContentEntity"
    SEQUENCEVARIANT = "SequenceVariant"
    SMALLMOLECULE = "SmallMolecule"
    ORGANISMTAXON = "OrganismTaxon"
    NUCLEICACIDENTITY = "NucleicAcidEntity"
    EVIDENCETYPE = "EvidenceType"
    GEOGRAPHICEXPOSURE = "GeographicExposure"
    RNAPRODUCT = "RNAProduct"
    TRANSCRIPT = "Transcript"
    FUNGUS = "Fungus"
    PLANT = "Plant"
    POPULATIONOFINDIVIDUALORGANISMS = "PopulationOfIndividualOrganisms"
    INVERTEBRATE = "Invertebrate"
    PROTEINDOMAIN = "ProteinDomain"
    PROTEINFAMILY = "ProteinFamily"
    ACTIVITY = "Activity"
    AGENT = "Agent"
    CHEMICALEXPOSURE = "ChemicalExposure"
    CONFIDENCELEVEL = "ConfidenceLevel"
    DATASET = "Dataset"
    ENVIRONMENTALFEATURE = "EnvironmentalFeature"
    EXON = "Exon"
    GENETICINHERITANCE = "GeneticInheritance"
    GENOME = "Genome"
    GENOTYPE = "Genotype"
    HAPLOTYPE = "Haplotype"
    HUMAN = "Human"
    INDIVIDUALORGANISM = "IndividualOrganism"
    MAMMAL = "Mammal"
    MATERIALSAMPLE = "MaterialSample"
    MICRORNA = "MicroRNA"
    PATENT = "Patent"
    PUBLICATION = "Publication"
    REGULATORYREGION = "RegulatoryRegion"
    STUDY = "Study"
    TREATMENT = "Treatment"
    WEBPAGE = "WebPage"
    ACCESSIBLEDNAREGION = "AccessibleDnaRegion"
    ARTICLE = "Article"
    ATTRIBUTE = "Attribute"
    BACTERIUM = "Bacterium"
    BIOLOGICALENTITY = "BiologicalEntity"
    BIOLOGICALSEX = "BiologicalSex"
    CELLLINE = "CellLine"
    CHEMICALMIXTURE = "ChemicalMixture"
    CODINGSEQUENCE = "CodingSequence"
    DATASETDISTRIBUTION = "DatasetDistribution"
    DIAGNOSTICAID = "DiagnosticAid"
    DRUGEXPOSURE = "DrugExposure"
    ENVIRONMENTALPROCESS = "EnvironmentalProcess"
    EVENT = "Event"
    GENOTYPICSEX = "GenotypicSex"
    NONCODINGRNAPRODUCT = "NoncodingRNAProduct"
    ORGANISMALENTITY = "OrganismalEntity"
    PHENOTYPICSEX = "PhenotypicSex"
    POLYPEPTIDE = "Polypeptide"
    PROCEDURE = "Procedure"
    PROCESSEDMATERIAL = "ProcessedMaterial"
    REAGENTTARGETEDGENE = "ReagentTargetedGene"
    SIRNA = "SiRNA"
    SNV = "Snv"
    STUDYVARIABLE = "StudyVariable"
    TRANSCRIPTIONFACTORBINDINGSITE = "TranscriptionFactorBindingSite"
    ZYGOSITY = "Zygosity"


class AssociationCategory(Enum):
    """Association categories"""

    PAIRWISEGENETOGENEINTERACTION = "PairwiseGeneToGeneInteraction"
    GENETOEXPRESSIONSITEASSOCIATION = "GeneToExpressionSiteAssociation"
    MACROMOLECULARMACHINETOBIOLOGICALPROCESSASSOCIATION = "MacromolecularMachineToBiologicalProcessAssociation"
    GENETOPHENOTYPICFEATUREASSOCIATION = "GeneToPhenotypicFeatureAssociation"
    MACROMOLECULARMACHINETOMOLECULARACTIVITYASSOCIATION = "MacromolecularMachineToMolecularActivityAssociation"
    MACROMOLECULARMACHINETOCELLULARCOMPONENTASSOCIATION = "MacromolecularMachineToCellularComponentAssociation"
    ASSOCIATION = "Association"
    GENETOGENEHOMOLOGYASSOCIATION = "GeneToGeneHomologyAssociation"
    DISEASETOPHENOTYPICFEATUREASSOCIATION = "DiseaseToPhenotypicFeatureAssociation"
    GENETOPATHWAYASSOCIATION = "GeneToPathwayAssociation"
    CHEMICALTOPATHWAYASSOCIATION = "ChemicalToPathwayAssociation"
    CORRELATEDGENETODISEASEASSOCIATION = "CorrelatedGeneToDiseaseAssociation"
    DISEASEORPHENOTYPICFEATURETOGENETICINHERITANCEASSOCIATION = (
        "DiseaseOrPhenotypicFeatureToGeneticInheritanceAssociation"
    )
    CAUSALGENETODISEASEASSOCIATION = "CausalGeneToDiseaseAssociation"
    CHEMICALTODISEASEORPHENOTYPICFEATUREASSOCIATION = "ChemicalToDiseaseOrPhenotypicFeatureAssociation"


class AssociationPredicate(Enum):
    """Association predicates"""

    INTERACTS_WITH = "interacts_with"
    EXPRESSED_IN = "expressed_in"
    HAS_PHENOTYPE = "has_phenotype"
    ENABLES = "enables"
    ACTIVELY_INVOLVED_IN = "actively_involved_in"
    ORTHOLOGOUS_TO = "orthologous_to"
    LOCATED_IN = "located_in"
    SUBCLASS_OF = "subclass_of"
    PARTICIPATES_IN = "participates_in"
    RELATED_TO = "related_to"
    ACTS_UPSTREAM_OF_OR_WITHIN = "acts_upstream_of_or_within"
    ACTIVE_IN = "active_in"
    PART_OF = "part_of"
    ACTS_UPSTREAM_OF = "acts_upstream_of"
    HAS_MODE_OF_INHERITANCE = "has_mode_of_inheritance"
    GENE_ASSOCIATED_WITH_CONDITION = "gene_associated_with_condition"
    CONTRIBUTES_TO = "contributes_to"
    CAUSES = "causes"
    COLOCALIZES_WITH = "colocalizes_with"
    ACTS_UPSTREAM_OF_OR_WITHIN_POSITIVE_EFFECT = "acts_upstream_of_or_within_positive_effect"
    ACTS_UPSTREAM_OF_POSITIVE_EFFECT = "acts_upstream_of_positive_effect"
    AFFECTS = "affects"
    ACTS_UPSTREAM_OF_OR_WITHIN_NEGATIVE_EFFECT = "acts_upstream_of_or_within_negative_effect"
    ACTS_UPSTREAM_OF_NEGATIVE_EFFECT = "acts_upstream_of_negative_effect"
