name: Build Images for Specific Branches

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name to build (leave empty to build current branch)'
        required: false
        type: string
  push:
    branches:
      # Add specific branch names here when needed for automatic builds
      # Example: - feature-xyz
      # Currently empty - use workflow_dispatch for on-demand builds

# This workflow builds images for specific branches for testing purposes
# Images are tagged with branch name and commit SHA but do not deploy anywhere
jobs:
  build-and-push-api-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Get branch name
        id: branch-name
        run: |
          if [ -n "${{ inputs.branch }}" ]; then
            BRANCH_NAME="${{ inputs.branch }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "Building branch: ${BRANCH_NAME}"

      - name: Build and Push Image
        uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
          registry: us-central1-docker.pkg.dev
          project_id: monarch-initiative
          image_name: monarch-api/monarch-api
          image_tag: ${{ steps.branch-name.outputs.BRANCH_NAME }}-${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./backend/Dockerfile

  build-and-push-frontend-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || github.ref }}
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install packages
        run: bun install

      - name: Build app
        run: bun run build

      - name: Get branch name
        id: branch-name
        run: |
          if [ -n "${{ inputs.branch }}" ]; then
            BRANCH_NAME="${{ inputs.branch }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "Building frontend for branch: ${BRANCH_NAME}"

      - name: Build and Push Image
        uses: RafikFarhad/push-to-gcr-github-action@v5-rc1
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}
          registry: us-central1-docker.pkg.dev
          project_id: monarch-initiative
          image_name: monarch-api/monarch-ui
          image_tag: ${{ steps.branch-name.outputs.BRANCH_NAME }}-${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./services/nginx/Dockerfile
          context: .

  # Note: This workflow does NOT deploy anywhere - it only builds images for testing
